import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import "../globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Pratijja 2024",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`bg-hero bg-cover bg-center bg-no-repeat`}
            >
                <div className="flex flex-col">
                    <div>{children}</div>
                </div>
                <Toaster />
            </body>
        </html>
    );
}
